config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations"}

  get '/', to: 'home#index', as: 'home'

  get '/admin', to: 'admin#projects', as: 'admin_projects'
  get '/admin/new_project', to: 'admin#new_project', as: 'admin_new_project'
  post '/admin', to: 'admin#create_project', as: 'admin_create_project'
  get '/admin/:id', to: 'admin#show_project', as: 'admin_show_project'
  get '/admin/:id/edit_project', to: 'admin#edit_project', as: 'admin_edit_project'
  patch '/admin/:id', to: 'admin#update_project', as: 'admin_update_project'
  delete '/admin/:id', to: 'admin#delete_project', as: 'admin_delete_project'

  get '/projects', to: 'projects#index', as: "projects"
  get '/projects/:id', to: 'projects#show', as: 'show_project'
  # resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord

  belongs_to :project

  has_attached_file :image,
    path: ":rails_root/public/images/:id/:filename",
    url: "/images/:id/:filename"

  do_not_validate_attachment_file_type :image
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :pictures, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def projects
    @projects = Project.all
  end

  def new_project
    @project = Project.new
  end

  def create_project
    @project = Project.new(project_params)

    respond_to do |format|

      if @project.save

        if params[:images]
          params[:images].each { |image|
          @project.pictures.create(image: image)
          }
        end
        format.html { redirect_to admin_projects_path, notice: "Proyecto creado con éxito" }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new"}
        format.json { render json: @project.errors, status: :unprocessable_entity}
      end
    end
  end

  def show_project
    @project = Project.find(params[:id])
  end

  def edit_project
    @project = Project.find(params[:id])
  end

  def update_project
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to admin_projects_path
    else
      render :edit
    end
  end

  def delete_project
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path
  end

  private

    def project_params
      params.require(:project).permit(:name, :location, :surface, :duration, :description, :image, :image_second, :image_third)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery with: :exception

  def index

  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  protect_from_forgery with: :exception

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

protected

def one_user_registered?
  if User.count == 1
    if user_signed_in?
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/_admin_project_card.html.erb
<div class="card project-card h-100">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% project.pictures.each_with_index do |img, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <img class="card-img-top d-block" src="<%= img.image.url %>" alt="Card image cap">
        </div>
      <% end %>
    </div>
  </div>

  <div class="card-body">
    <h5 class="card-title"> <%= project.name %> </h5>
    <p class="card-text"> <%= project.location %> </p>
    <p class="card-text"> <%= project.surface %> </p>
    <%= link_to t('show'), admin_show_project_path(project), class: "btn btn-info" %>
    <%= link_to t('edit'), admin_edit_project_path(project), class: "btn btn-primary" %>
    <%= link_to t('delete'), admin_delete_project_path(project), class: "btn btn-danger", method: :delete, data: {confirm: t('are_you_sure')} %>
  </div>
</div>

app/views/admin/edit_project.html.erb
<%= form_for @project, url: {action: "update_project"} do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :surface %>
  <%= f.text_field :surface, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :pictures %>
    <%= file_field_tag "images[]", type: :file, multiple: true, class: "form-control" %>
</div>

<div>
  <%= f.submit t('save'), :class => "btn btn-primary" %>
</div>

<% end %>

app/views/admin/new_project.html.erb
<%= form_for @project, url: {action: "create_project"}, html: { class: "form-horizontal", multipart: true } do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :surface %>
  <%= f.text_field :surface, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :pictures %>
    <%= file_field_tag "images[]", type: :file, multiple: true, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit nil, class: "btn btn-success" %>
  <%= link_to t('.cancel', default: t('helpers.links.cancel')),
      admin_projects_path, class: "btn btn-mini" %>
</div>

<% end %>

app/views/admin/projects.html.erb
<div class="row">
  <div class="col">
    <h1><%= t('project_list') %></h1>
  </div>
  <div class="col">
    <div class="pull-right">
      <%= link_to t('new_project'), admin_new_project_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="row">
    <% @projects.each_with_index do |project, index| %>
    <div class="col-3 project-card-col mb-5">
      <%= render 'admin_project_card', project: project %>
    </div>
    <%end%>
</div>


<% content_for :footer do %>

<script>

$(document).ready(function() {

  $('.project-card-col').hover(
    function(){
      $(this).animate({
        marginTop: "-4px",
      }, 200)
    },
    function(){
      $(this).animate({
        marginTop: "0%"
      }, 200)
    }
  );

});

</script>

<% end %>

app/views/admin/show_project.html.erb
<div class="row">
  <div class="col">
    <h3> <%= @project.name %> </h3>
    <p> <%= @project.location %> </p>
    <p> <%= @project.surface %> </p>
    <p> <%= @project.duration %> </p>
    <p> <%= @project.description %> </p>
    <div class="project-gallery">
      <% @project.pictures.each do |img| %>
        <div class="gallery-item">
          <img class="gallery-image" src="<%= img.image.url %>" alt="First slide">
        </div>
      <% end %>
    </div>
    <%= link_to t('project_list'), admin_projects_path, class: "btn btn-info" %>
  </div>
</div>

app/views/application/_footer.html.erb
<footer id="main-footer" class="bg-dark">
  <div class="container-fluid">
    <div class="row">
      <div class="col text-center">
        <div class="py-4">
          <h1 class="h3">Vica SL</h1>
          <p>Copyright &copy; 2013</p>
          <button class="btn btn-primary" data-toggle="modal" data-target="#contactModal">Contact Us</button>
          <a href="<%=admin_projects_path%>">Acceso intranet</a>
        </div>
      </div>
    </div>
  </div>
</footer>

<div class="modal fade text-dark" id="contactModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contactModalTitle">
          Contact Us
        </h5>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary btn-block">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/application/_header.html.erb
<header id="header-section">
  <div class="dark-overlay">
    <div class="home-inner">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 d-none d-lg-block">
            <h3> <%=t('slogan')%></h3>
            <div class="d-flex flex-row">
              <div class="p-4 align-self-start">
                <i class="fa fa-check"></i>
              </div>
              <div class="p-4 align-self-end">
                <%=t('header_point_1') %>
              </div>
            </div>
            <div class="d-flex flex-row">
              <div class="p-4 align-self-start">
                <i class="fa fa-check"></i>
              </div>
              <div class="p-4 align-self-end">
                <%=t('header_point_2') %>
              </div>
            </div>
            <div class="d-flex flex-row">
              <div class="p-4 align-self-start">
                <i class="fa fa-check"></i>
              </div>
              <div class="p-4 align-self-end">
                <%=t('header_point_3') %>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="card bg-primary text-center card-form">
              <div class="card-body">
                <h3><%=t('sign_up_today')%></h3>
                <p><%=t('form_register')%></p>
                <%= render 'devise/registrations/new' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
  <div class="container-fluid">
    <a href="/" class="navbar-brand">
      <img src="<%=asset_path('vica-sl-logo.svg')%>" width="30" height="30" class="d-inline-block align-top vica-logo" alt="">
    </a>
    <% if user_signed_in? %>
    <span> <%= t('signed_in_with') %> <strong><%= current_user.email %></strong> </span>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="<%=home_path%>" class="nav-link"><%=t('home')%></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle project-dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%=t('services')%>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><%=t('living_place')%></a>
            <a class="dropdown-item" href="#"><%=t('commercial')%></a>
            <a class="dropdown-item" href="#"><%=t('rehabilitation')%></a>
            <a class="dropdown-item" href="#"><%=t('public_equipment')%></a>
            <a class="dropdown-item" href="#"><%=t('industry')%></a>
          </div>
        </li>
        <li class="nav-item">
          <a href="<%=projects_path%>" class="nav-link"><%=t('projects')%></a>
        </li>
        <li class="nav-item">
          <a href="#create-head-section" class="nav-link"><%=t('about_us')%></a>
        </li>
        <li class="nav-item">
          <a href="#share-head-section" class="nav-link"><%=t('clients')%></a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <a href="<%=admin_projects_path%>" class="btn btn-primary"><%= t('admin') %></a>
        </li>
        <li class="nav-item">
          <%= link_to t('edit_profile'), edit_user_registration_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('log_out'), destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% content_for :footer do %>

<script>

$( document ).ready(function() {
  $('.project-dropdown').dropdown();

});

</script>

<% end %>

app/views/home/index.html.erb
<%= render '/application/header' %>

<section id="explore-head-section">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <div class="p-5">
          <h1 class="display-4">Explore</h1>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam officiis eveniet velit tempora laboriosam architecto alias aspernatur nemo porro soluta.</p>
          <a href="#" class="btn btn-outline-secondary">Find Out More</a>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="explore-section" class="bg-light text-muted py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="<%=asset_path('architecture-explore.jpg')%>" alt="" class="img-fluid mb-3 rounded-circle">
      </div>
      <div class="col-md-6">
        <h3>Explore & Connect</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem reiciendis veritatis quis? Doloremque perspiciatis voluptatum facilis aliquam placeat ullam repudiandae temporibus possimus non amet doloribus eaque, libero, sapiente voluptatem velit!</p>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="create-head-section" class="bg-primary">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <div class="p-5">
          <h1 class="display-4">Create</h1>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam officiis eveniet velit tempora laboriosam architecto alias aspernatur nemo porro soluta.</p>
          <a href="#" class="btn btn-outline-light">Find Out More</a>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="create-section" class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h3>Create Your Passion</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem reiciendis veritatis quis? Doloremque perspiciatis voluptatum facilis aliquam placeat ullam repudiandae temporibus possimus non amet doloribus eaque, libero, sapiente voluptatem velit!</p>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <img src="<%=asset_path('flat-create.jpg')%>" alt="" class="img-fluid mb-3 rounded-circle">
      </div>
    </div>
  </div>
</section>

<section id="share-head-section" class="bg-primary">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <div class="p-5">
          <h1 class="display-4">Share</h1>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam officiis eveniet velit tempora laboriosam architecto alias aspernatur nemo porro soluta.</p>
          <a href="#" class="btn btn-outline-light">Find Out More</a>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="share-section" class="bg-light text-muted py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="<%=asset_path('builders-share.jpg')%>" alt="" class="img-fluid mb-3 rounded-circle">
      </div>
      <div class="col-md-6">
        <h3>Share what you create</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem reiciendis veritatis quis? Doloremque perspiciatis voluptatum facilis aliquam placeat ullam repudiandae temporibus possimus non amet doloribus eaque, libero, sapiente voluptatem velit!</p>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
        <div class="d-flex flex-row">
          <div class="p-4 align-self-start">
            <i class="fa fa-check"></i>
          </div>
          <div class="p-4 align-self-end">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic qui earum maiores aut voluptatibus accusamus?
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vica Constructors</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body id="home">


    <%= render '/application/navbar' %>

      <div class="main-panel">
          <% if notice %>
            <p class="alert alert-success" role="alert"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger" role="alert"><%= alert %></p>
          <% end %>

          <%= yield %>
      </div>


    <%= render '/application/footer' %>

    <%= yield :footer%>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product, url: {action: "update"} do |f| %>

<div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image_second %>
  <%= f.text_field :image_second, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image_third %>
  <%= f.text_field :image_third, class: "form-control" %>
</div>

<div>
  <%= f.submit t('save'), :class => "btn btn-primary" %>
</div>

<% end %>

app/views/products/index.html.erb
<div class="row">
  <div class="col">
    <h1><%= t('product_list') %></h1>
  </div>
  <div class="col">
    <div class="pull-right">
      <%= link_to t('new_product'), products_new_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="row">
    <% @products.each_with_index do |product, index| %>
    <div class="col-3 product-card-col mb-5">
      <%= render 'product_card', product: product %>
    </div>
    <%end%>
</div>


<% content_for :footer do %>

<script>

$(document).ready(function() {

  $('.product-card-col').hover(
    function(){
      $(this).animate({
        marginTop: "-4px",
      }, 200)
    },
    function(){
      $(this).animate({
        marginTop: "0%"
      }, 200)
    }
  );

});

</script>

<% end %>

app/views/products/new.html.erb
<%= form_for @product, url: {action: "create"} do |f| %>

<div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image_second %>
  <%= f.text_field :image_second, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image_third %>
  <%= f.text_field :image_third, class: "form-control" %>
</div>

<div>
  <%= f.submit "Create", :class => "btn btn-success" %>
</div>

<% end %>

app/views/projects/_project_card.html.erb
<div class="card project-card h-100">
  <img class="card-img-top" src="<%=project.image%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"> <%= project.name %> </h5>
    <p class="card-text"> <%= project.location %> </p>
    <p class="card-text"> <%= project.surface %> </p>
    <p class="card-text"> <%= project.duration %> </p>
    <p class="card-text"> <%= project.description %> </p>
    <%= link_to t('show'), show_project_path(project), class: "btn btn-info" %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col">
    <h1><%= t('project_list') %></h1>
  </div>
</div>

<div class="row">
    <% @projects.each_with_index do |project, index| %>
    <div class="col-3 project-card-col mb-5">
      <%= render 'project_card', project: project %>
    </div>
    <%end%>
</div>


<% content_for :footer do %>

<script>

$(document).ready(function() {

  $('.project-card-col').hover(
    function(){
      $(this).animate({
        marginTop: "-4px",
      }, 200)
    },
    function(){
      $(this).animate({
        marginTop: "0%"
      }, 200)
    }
  );

});

</script>

<% end %>

app/views/projects/show.html.erb
<div class="row">
  <div class="col">
    <div id="projectSlider" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100 slide-image" src="<%= @project.image %>" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 slide-image" src="<%= @project.image_second %>" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 slide-image" src="<%= @project.image_third %>" alt="Third slide">
        </div>
      </div>
    </div>
    <h3> <%= @project.name %> </h3>
    <p> <%= @project.description %> </p>
    <%= link_to t('project_list'), projects_path, class: "btn btn-info" %>
  </div>
</div>

<% content_for :footer do %>

<script type="text/javascript">

$( document ).ready(function() {

  $('.carousel').carousel();

});

</script>

<% end %>